// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZXbI7vjw3KSRt5Tu5Wuuq5AgEpUWmCM',
    appId: '1:797561880038:web:abcd62b228c84d0105aa27',
    messagingSenderId: '797561880038',
    projectId: 'commonshub-55f08',
    authDomain: 'commonshub-55f08.firebaseapp.com',
    storageBucket: 'commonshub-55f08.firebasestorage.app',
    measurementId: 'G-Q7N44QVEYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3IYB0wr-CJDONyB1QIliK6YDgSsbyC40',
    appId: '1:797561880038:android:e46f68a4a1c8fcec05aa27',
    messagingSenderId: '797561880038',
    projectId: 'commonshub-55f08',
    storageBucket: 'commonshub-55f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOj5vRC_k75yVAO0k8wp9xFSY_VwVnb6s',
    appId: '1:797561880038:ios:852eb4f7cad240c705aa27',
    messagingSenderId: '797561880038',
    projectId: 'commonshub-55f08',
    storageBucket: 'commonshub-55f08.firebasestorage.app',
    iosBundleId: 'com.example.socialAppFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOj5vRC_k75yVAO0k8wp9xFSY_VwVnb6s',
    appId: '1:797561880038:ios:852eb4f7cad240c705aa27',
    messagingSenderId: '797561880038',
    projectId: 'commonshub-55f08',
    storageBucket: 'commonshub-55f08.firebasestorage.app',
    iosBundleId: 'com.example.socialAppFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ZXbI7vjw3KSRt5Tu5Wuuq5AgEpUWmCM',
    appId: '1:797561880038:web:6588844b56c3844c05aa27',
    messagingSenderId: '797561880038',
    projectId: 'commonshub-55f08',
    authDomain: 'commonshub-55f08.firebaseapp.com',
    storageBucket: 'commonshub-55f08.firebasestorage.app',
    measurementId: 'G-16VXCZ6H37',
  );
}
