enum NotificationType {
  FRIEND_REQUEST,
  FRIEND_ACCEPT,
  NEW_POST,
  POST_COMMENT,
  POST_REACTION,
  MENTION,
  STORY_REACTION,
  COMMENT_REACTION,
  POST_REPORT_REVIEWED, // Admin đã xử lý báo cáo
  FACE_DETECTED, // Phát hiện khuôn mặt
  TAG_POST, // Được gắn thẻ
  FACE_TAG_SUGGEST, // Gợi ý gắn thẻ từ AI

  COMMUNITY_PUBLIC_JOIN,
  COMMUNITY_JOIN_REQUEST,
  COMMUNITY_INVITE,
  COMMUNITY_JOIN_APPROVED,
  COMMUNITY_JOIN_REJECTED,
  COMMUNITY_POST_APPROVED,
  COMMUNITY_POST_REJECTED,
  COMMUNITY_POST_PENDING,
  UNKNOWN,
}
